apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorenz-deployment
  labels:
    app: lorenz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lorenz-app
  template:
    metadata:
      labels:
        app: lorenz-app
    spec:
      containers:
      - name: lorenz-container
        image: artmen/lorenz:latest
        ports:
        - containerPort: 1234
        