apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorenz-deployment
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: lorenz
        image: artmen/lorenz:latest
        ports:
        - containerPort: 1234
        